apiVersion: v1
kind: Pod
metadata:
  name: demo-golang-docker
  labels:
    name: demo-golang-docker
spec:
  containers:
  - name: demo-golang-docker
    image: pablon27/demo-golang-docker:0.0.2.SNAPSHOT
    ports:
      - containerPort: 8080
    readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 8

