apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  volumes:
  - name: foo
    secret:
     secretName: mysecret 
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: foo
      mountPath: /etc/foo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
