apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blueg"
      effect: NoSchedule