apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx
    type: front-end
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        type: front-end
    spec:
      containers:
        - name: nginx-controller
          image: nginx
  replicas: 5
  selector:
    matchLabels:
      type: front-end
