apiVersion: v1
kind: Pod
metadata:
  name: hello-world-2
  labels:
    name: hello-world-2
spec:
  containers:
  - name: hello-world-2
    image: pablon27/hello-world-js:1.0.0
    ports:
      - containerPort: 8080
    envFrom:
      - secretRef:
         name: app-secret