apiVersion: v1
kind: Pod
metadata:
  name: debian-command
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: debian-command
    image: debian
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure

