apiVersion: v1
kind: Pod
metadata:
  name: debian-command
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: debian-command
    image: debian
    env:
    - name: MESSAGE
      value: "hello world"
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
  restartPolicy: OnFailure
  
