apiVersion: v1
kind: Pod
metadata:
  name: hello-world-3
  labels:
    name: hello-world-3
spec:
  containers:
  - name: hello-world-3
    image: pablon27/hello-world-js:1.0.0
    ports:
      - containerPort: 8080
  volumes:
    - name: app-secret-volume
      secret:
        secretName: app-secret